name: Build JAR > Upload to S3 - Shipping Microservice

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull from ${{ github.repository }}
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        #cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml   
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Copy jar to ms-shipping S3 folder
      run: | 
       mkdir -p ~/deploys/${{ secrets.MS_SHIPPING_FOLDER }}
       cp /home/runner/work/MS-Orders/MS-Orders/target/*.jar ~/deploys/${{ secrets.MS_SHIPPING_FOLDER }}/
       
    - name: Upload Jar files to the S3 Bucket
      run: |
        aws s3 sync ~/deploys s3://${{ secrets.AWS_BUCKET }}
