# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name:  Build JAR and Upload to S3 - Shipping Microservice

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull from ${{ github.repository }}
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - uses: szenius/set-timezone@v1.0
      with:
       timezoneLinux: "America/Montevideo"


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Set current date as env variable and create jars folder
      run: | 
       export DATE=build-$(date +'%d-%m-%Y_%T')
       echo "DATE=$DATE" >> $GITHUB_ENV
       mkdir -p ~/deploys/${{ secrets.MS_SHIPPING_FOLDER }}/$DATE
       cp /home/runner/work/MS-Shipping/MS-Shipping/target/shipping-service-example-0.0.1-spring-boot.jar ~/deploys/${{ secrets.MS_SHIPPING_FOLDER }}/$DATE/    
       
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync ~/deploys s3://${{ secrets.AWS_BUCKET }}


