name: Upload JAR to S3 - Shipping Microservice

on:
  push:
    branches: [ "master" ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ASIAU4AK33JPNY4YSHJ6
          aws-secret-access-key: xOVuMrUTYh1OuvCuiL//1AHCMW8fHNsc2AIEuO8G
          aws-region: 'us-east-1'
          aws-bucket: obligatorio-devops-danya-hernan
          file-path: './target/'
