name: Upload JAR to S3 - Shipping Microservice

on:
  push:
    branches: [ "master" ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: 'AKIAY3KL6NMR3DI4YPEW'
          aws-secret-access-key: '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'
          aws-region: 'us-east-1'
          aws-bucket: 'obligatorio-devops-danya-hernan2'
          file-path: './README.md'
